// src/sandbox/recordings.js -- GENERATED by tools/fetch-audio.js from
// tools/audio-manifest.json. One import per recording, in manifest order.
// Edit the manifest, not this file.
import './recordedFurElise.js';
import './recordedMoonlight.js';
import './recordedSymphony5.js';
import './recordedGoldbergAria.js';
import './recordedMountainKing.js';
import './recordedWilliamTell.js';
import './recordedGymnopedie.js';
import './recordedNachtmusik.js';
import './recordedBaldMountain.js';
